### ISSUE TITLE
Typo inside bin/index.js

### ISSUE THREAD

**Issue by JohnPCarvalho** [utopiops/utopiops#18]
Hi! Good afternoon to you all!

In the line 10 of index.js, the `.command('creat')`is wrong. Wouldn't be `.command('create')`?
If it's wrong, I can fork the project and push the fix.

Please ignore and close this issue if I'm wrong. Thanks!!

**Comment by mkamrani** [comment]
Hi John, good catch. Thanks for reporting the issue.
